### ISSUE TITLE
Replace f-strings with Jinja templates for .yml and .sh creation

### ISSUE THREAD

**Issue by foprel** [jschra/grater_expectations#2]
The project uses several functions to dynamically generate config files and bash scripts. It does this by using long multiline f-strings inside `intialize_project.py`. This is not ideal for readability and maintenance.

I suggest to separate these "generator" functions from their related templates. The function that is called to generate the config files and bash scripts can remain in `initialize_project.py`, while the actual templates are stored elsewhere. This can be achieved with [Jinja](https://jinja.palletsprojects.com/en/3.1.x/).

**Comment by jschra** [comment]
Also fixed by your PR. Great job!
