### ISSUE TITLE
Add command to retreive the package version

### ISSUE THREAD

**Issue by foprel** [jschra/grater_expectations#3]
If PR #1  is merged with the main branch and distributed via PyPI, it is probably useful to add a command line feature to show the current package version. GitHub and PyPI might not be in sync, so this will help with debugging later on. It could be as simple as:

```
parser.add_argument('-v', '--version', action='version', version='1.0.0.0')
```

However, I recommend to get the version number from the `setup.py` file instead. [This](https://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package) discussion on Stackoverflow lists a few options on how to get the package version at runtime.

**Comment by jschra** [comment]
You fixed this w/ your PR. Great job!
